name: CI/CD Pipeline for Pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.12

      - name: Install system dependencies for Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip
          sudo apt-get install -y libxss1 libappindicator3-1 libindicator7
          sudo apt-get install -y google-chrome-stable

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install pytest selenium webdriver-manager

      - name: Run tests with pytest
        run: |
          pytest -v -rA
